### ISSUE TITLE
USDT(Trc20) Validation

### ISSUE THREAD

**Issue by sniper365** [christsim/multicoin-address-validator#84]
I tried like below

const valid = WAValidator.validate('TUTtVjNqCj3fndQ29YFKEdXvWwBwFihk1G', 'usdt', 'Tron')

console.log(valid) -> false

Could you assist me how to validate usdt on BSC, TRX, SOL, POLYGON, ..?

**Comment by juanmanso** [comment]
If you check how USDT's validator is implemented, it's only using BTC and ETH validators.

Have you tried using `Tron` instead of USDT?

By using the Tron validator, it worked for me:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/21087992/215420786-a4a53500-49e4-476f-b844-75c811bb5e5a.png">

**Comment by christsim** [comment]
fixed in 0.5.16
